#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling your project before committing 👷‍♂️🏗️'

# Run ESLint
pnpm run lint ||
(
    echo '🔨❌ You have a problem in your code. Check the linter ❌🔨';
    false;
)

# Run Prettier
pnpm run format

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'
